# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Frog.create!([
  { :name => "Samuel", :color => "Dark Green", :pond_id => 2, :created_at => "2013-11-04 01:32:26", :updated_at => "2013-11-04 17:50:12", :fly_count => 2 },
  { :name => "Aaron", :color => "Yellow", :pond_id => 2, :created_at => "2013-11-04 01:32:26", :updated_at => "2013-11-04 01:32:26", :fly_count => 0 },
  { :name => "Betty", :color => "Brown", :pond_id => 3, :created_at => "2013-11-04 01:32:26", :updated_at => "2013-11-04 01:32:26", :fly_count => 0 },
  { :name => "Alice", :color => "Blue", :pond_id => 2, :created_at => "2013-11-04 01:32:26", :updated_at => "2013-11-04 01:32:26", :fly_count => 0 },
  { :name => "Dilbert", :color => "Yellow", :pond_id => 1, :created_at => "2013-11-04 01:32:26", :updated_at => "2013-11-04 01:32:26", :fly_count => 0 },
  { :name => "mr frog", :color => "purple", :pond_id => 1, :created_at => "2013-11-04 15:51:01", :updated_at => "2013-11-04 15:51:01", :fly_count => 0 },
  { :name => "Ms Frog", :color => "Pink", :pond_id => 3, :created_at => "2013-11-04 16:10:57", :updated_at => "2013-11-04 16:10:57", :fly_count => 0 },
  { :name => "Birdie", :color => "Yellow", :pond_id => 2, :created_at => "2013-11-04 17:51:45", :updated_at => "2013-11-04 17:51:45", :fly_count => 0 },
  { :name => "Jessica", :color => "Green", :pond_id => 2, :created_at => "2013-11-04 19:04:36", :updated_at => "2013-11-04 19:04:36", :fly_count => 0 },
  { :name => "Jenn", :color => "Brown", :pond_id => 3, :created_at => "2013-11-04 19:38:20", :updated_at => "2013-11-04 19:38:20", :fly_count => 0 },
  { :name => "Octocat", :color => "black", :pond_id => 1, :created_at => "2013-11-04 20:11:49", :updated_at => "2013-11-04 20:11:49", :fly_count => 0 },
  { :name => "Mr. Frog", :color => "Green", :pond_id => 3, :created_at => "2013-11-04 20:22:42", :updated_at => "2013-11-04 20:22:42", :fly_count => 0 },
  { :name => "Samuel Jr.", :color => "Green", :pond_id => 2, :created_at => "2013-11-04 21:01:01", :updated_at => "2013-11-04 21:01:01", :fly_count => 0 }
])



Pond.create!([
  { :name => "White Frost", :water_type => "Glass", :created_at => "2013-11-04 01:32:26", :updated_at => "2013-11-04 19:30:49" },
  { :name => "Sunny Meadow", :water_type => "Blue", :created_at => "2013-11-04 01:32:26", :updated_at => "2013-11-04 01:32:26" },
  { :name => "Greenwood", :water_type => "Murky", :created_at => "2013-11-04 01:32:26", :updated_at => "2013-11-04 01:32:26" }
])



Tadpole.create!([
  { :name => "Beth", :color => "Yellow", :frog_id => 2, :created_at => "2013-11-04 01:32:26", :updated_at => "2013-11-04 01:32:26" },
  { :name => "Brad", :color => "Blue", :frog_id => 4, :created_at => "2013-11-04 01:32:26", :updated_at => "2013-11-04 01:32:26" },
  { :name => "Lewis", :color => "Yellow", :frog_id => 5, :created_at => "2013-11-04 01:32:26", :updated_at => "2013-11-04 01:32:26" },
  { :name => "Friendliest", :color => "Green", :frog_id => 1, :created_at => "2013-11-04 01:32:26", :updated_at => "2013-11-04 19:30:28" },
  { :name => "Simon", :color => "Brown", :frog_id => 2, :created_at => "2013-11-04 01:32:26", :updated_at => "2013-11-04 18:48:12" },
  { :name => "Grumpy", :color => "Brown", :frog_id => 1, :created_at => "2013-11-04 21:01:19", :updated_at => "2013-11-04 21:01:19" }
])


